[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Netsuite Excens"
authors = [{name = "Javi ", email = "Javier.martin@excens.com"}]
dynamic = ["version", "description"]
